<a href="https://colab.research.google.com/github/jbliaw/QM323/blob/main/GitHub_AutomatingConjointRegressions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install watermark

Collecting watermark
  Downloading https://files.pythonhosted.org/packages/60/fe/3ed83b6122e70dce6fe269dfd763103c333f168bf91037add73ea4fe81c2/watermark-2.0.2-py2.py3-none-any.whl
Requirement already satisfied: ipython in /usr/local/lib/python3.6/dist-packages (from watermark) (5.5.0)
Requirement already satisfied: setuptools>=18.5 in /usr/local/lib/python3.6/dist-packages (from ipython->watermark) (50.3.0)
Requirement already satisfied: traitlets>=4.2 in /usr/local/lib/python3.6/dist-packages (from ipython->watermark) (4.3.3)
Requirement already satisfied: pexpect; sys_platform != "win32" in /usr/local/lib/python3.6/dist-packages (from ipython->watermark) (4.8.0)
Requirement already satisfied: decorator in /usr/local/lib/python3.6/dist-packages (from ipython->watermark) (4.4.2)
Requirement already satisfied: simplegeneric>0.8 in /usr/local/lib/python3.6/dist-packages (from ipython->watermark) (0.8.1)
Requirement already satisfied: pygments in /usr/local/lib/python3.6/dist-packages (from ipython->watermark) (2.6.1)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.6/dist-packages (from ipython->watermark) (0.7.5)
Requirement already satisfied: prompt-toolkit<2.0.0,>=1.0.4 in /usr/local/lib/python3.6/dist-packages (from ipython->watermark) (1.0.18)
Requirement already satisfied: ipython-genutils in /usr/local/lib/python3.6/dist-packages (from traitlets>=4.2->ipython->watermark) (0.2.0)
Requirement already satisfied: six in /usr/local/lib/python3.6/dist-packages (from traitlets>=4.2->ipython->watermark) (1.15.0)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.6/dist-packages (from pexpect; sys_platform != "win32"->ipython->watermark) (0.6.0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.6/dist-packages (from prompt-toolkit<2.0.0,>=1.0.4->ipython->watermark) (0.2.5)
Installing collected packages: watermark
Successfully installed watermark-2.0.2

In [2]:
%load_ext watermark

In [14]:
%watermark

2020-10-07T02:49:24+00:00

CPython 3.6.9
IPython 5.5.0

compiler   : GCC 8.4.0
system     : Linux
release    : 4.19.112+
machine    : x86_64
processor  : x86_64
CPU cores  : 2
interpreter: 64bit

- NOTE: Please make a copy of this file for yourself (it's like a google doc). That way you can edit as you need, and it won't interfere with other runs. 
- Before you start, prep the data for regression in excel (basically Conjoint Tutorial as posted in Conjoint Workshop QM 11 folder): 
     - transpose direct data from Qualtrics
     - download "dummy variables for conjoint analysis regressions" on QTools
     - copy and paste customers to "dummy variables..." excel file (see JetOrange example)
     - rename file to 'conjointdata.xlsx' so that you can upload to Google Colab
- Then upload the file: 
     - click folder icon to the left
     - right click in white space (or regular click page with arrow icon) and upload 'conjointdata.xlsx'
     - click each 'play'/run button (more instructions as #comments in each code block)

## General Prep

In [4]:
from getpass import getpass
username = getpass('Username:')
password = getpass('Password:')

Username:··········
Password:··········

In [6]:
!if [ -d QM323 ]; then rm -Rf QM323; fi
!git clone https://$username:$password@github.com/jbliaw/QM323.git
!pip install ./QM323

Cloning into 'QM323'...
remote: Enumerating objects: 17, done.
remote: Counting objects: 100% (17/17), done.
remote: Compressing objects: 100% (13/13), done.
remote: Total 17 (delta 2), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (17/17), done.
Processing ./QM323
Building wheels for collected packages: not-DML
  Building wheel for not-DML (setup.py) ... done
  Created wheel for not-DML: filename=not_DML-0.1.0-cp36-none-any.whl size=1007 sha256=25ffd0d32e872bb9b736f03093bdf77074e4ea53704363028f24e78c8039ece8
  Stored in directory: /tmp/pip-ephem-wheel-cache-ecxg4pmh/wheels/e1/02/40/d3e1bdbb380378b139553229b569b0e5bde39f5c48baa084b8
Successfully built not-DML
Installing collected packages: not-DML
Successfully installed not-DML-0.1.0

In [8]:
# Necessary imports
import pandas as pd
import pandas.testing as tm
import statsmodels.api as sm
import statsmodels.formula.api as smf
from QM323.Functions.automateregression import AutomateRegression

In [9]:
# Read in data
df = pd.read_excel('/content/QM323/conjointdata.xlsx')
print(df.shape) # (rows, columns)
df.head() # Take a look at the data

(9, 49)

   Profile  Price high  Price low  ...  Customer41  Customer42  Customer43
0        1           1          0  ...           3           2           6
1        2           0          0  ...           2           2           3
2        3           0          0  ...           2           2           4
3        4           1          0  ...           3           2           3
4        5           1          0  ...           3           2           6

[5 rows x 49 columns]

In [11]:
theresults = AutomateRegression.automateregression(df)

/usr/local/lib/python3.6/dist-packages/scipy/stats/stats.py:1535: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  "anyway, n=%i" % int(n))
/usr/local/lib/python3.6/dist-packages/statsmodels/regression/linear_model.py:1636: RuntimeWarning: divide by zero encountered in double_scalars
  return 1 - self.ssr/self.centered_tss
/usr/local/lib/python3.6/dist-packages/scipy/stats/stats.py:1535: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  "anyway, n=%i" % int(n))
/usr/local/lib/python3.6/dist-packages/scipy/stats/stats.py:1535: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  "anyway, n=%i" % int(n))
/usr/local/lib/python3.6/dist-packages/statsmodels/regression/linear_model.py:1636: RuntimeWarning: divide by zero encountered in double_scalars
  return 1 - self.ssr/self.centered_tss
/usr/local/lib/python3.6/dist-packages/scipy/stats/stats.py:1535: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  "anyway, n=%i" % int(n))
/usr/local/lib/python3.6/dist-packages/statsmodels/regression/linear_model.py:1636: RuntimeWarning: divide by zero encountered in double_scalars
  return 1 - self.ssr/self.centered_tss
/usr/local/lib/python3.6/dist-packages/scipy/stats/stats.py:1535: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  "anyway, n=%i" % int(n))
/usr/local/lib/python3.6/dist-packages/scipy/stats/stats.py:1535: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  "anyway, n=%i" % int(n))
/usr/local/lib/python3.6/dist-packages/scipy/stats/stats.py:1535: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  "anyway, n=%i" % int(n))
/usr/local/lib/python3.6/dist-packages/scipy/stats/stats.py:1535: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  "anyway, n=%i" % int(n))
/usr/local/lib/python3.6/dist-packages/scipy/stats/stats.py:1535: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  "anyway, n=%i" % int(n))
/usr/local/lib/python3.6/dist-packages/scipy/stats/stats.py:1535: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  "anyway, n=%i" % int(n))
/usr/local/lib/python3.6/dist-packages/scipy/stats/stats.py:1535: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  "anyway, n=%i" % int(n))
/usr/local/lib/python3.6/dist-packages/scipy/stats/stats.py:1535: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  "anyway, n=%i" % int(n))
/usr/local/lib/python3.6/dist-packages/scipy/stats/stats.py:1535: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  "anyway, n=%i" % int(n))
/usr/local/lib/python3.6/dist-packages/scipy/stats/stats.py:1535: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  "anyway, n=%i" % int(n))
/usr/local/lib/python3.6/dist-packages/scipy/stats/stats.py:1535: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  "anyway, n=%i" % int(n))
/usr/local/lib/python3.6/dist-packages/scipy/stats/stats.py:1535: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  "anyway, n=%i" % int(n))
/usr/local/lib/python3.6/dist-packages/scipy/stats/stats.py:1535: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  "anyway, n=%i" % int(n))
/usr/local/lib/python3.6/dist-packages/scipy/stats/stats.py:1535: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  "anyway, n=%i" % int(n))
/usr/local/lib/python3.6/dist-packages/scipy/stats/stats.py:1535: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  "anyway, n=%i" % int(n))
/usr/local/lib/python3.6/dist-packages/scipy/stats/stats.py:1535: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  "anyway, n=%i" % int(n))
/usr/local/lib/python3.6/dist-packages/scipy/stats/stats.py:1535: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  "anyway, n=%i" % int(n))
/usr/local/lib/python3.6/dist-packages/scipy/stats/stats.py:1535: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  "anyway, n=%i" % int(n))
/usr/local/lib/python3.6/dist-packages/scipy/stats/stats.py:1535: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  "anyway, n=%i" % int(n))
/usr/local/lib/python3.6/dist-packages/scipy/stats/stats.py:1535: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  "anyway, n=%i" % int(n))
/usr/local/lib/python3.6/dist-packages/scipy/stats/stats.py:1535: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  "anyway, n=%i" % int(n))
/usr/local/lib/python3.6/dist-packages/scipy/stats/stats.py:1535: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  "anyway, n=%i" % int(n))
/usr/local/lib/python3.6/dist-packages/scipy/stats/stats.py:1535: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  "anyway, n=%i" % int(n))
/usr/local/lib/python3.6/dist-packages/scipy/stats/stats.py:1535: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  "anyway, n=%i" % int(n))
/usr/local/lib/python3.6/dist-packages/scipy/stats/stats.py:1535: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  "anyway, n=%i" % int(n))
/usr/local/lib/python3.6/dist-packages/scipy/stats/stats.py:1535: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  "anyway, n=%i" % int(n))
/usr/local/lib/python3.6/dist-packages/scipy/stats/stats.py:1535: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  "anyway, n=%i" % int(n))
/usr/local/lib/python3.6/dist-packages/scipy/stats/stats.py:1535: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  "anyway, n=%i" % int(n))
/usr/local/lib/python3.6/dist-packages/scipy/stats/stats.py:1535: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  "anyway, n=%i" % int(n))
/usr/local/lib/python3.6/dist-packages/scipy/stats/stats.py:1535: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  "anyway, n=%i" % int(n))
/usr/local/lib/python3.6/dist-packages/scipy/stats/stats.py:1535: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  "anyway, n=%i" % int(n))
/usr/local/lib/python3.6/dist-packages/scipy/stats/stats.py:1535: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  "anyway, n=%i" % int(n))
/usr/local/lib/python3.6/dist-packages/scipy/stats/stats.py:1535: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  "anyway, n=%i" % int(n))
/usr/local/lib/python3.6/dist-packages/scipy/stats/stats.py:1535: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  "anyway, n=%i" % int(n))
/usr/local/lib/python3.6/dist-packages/scipy/stats/stats.py:1535: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  "anyway, n=%i" % int(n))
/usr/local/lib/python3.6/dist-packages/scipy/stats/stats.py:1535: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  "anyway, n=%i" % int(n))
/usr/local/lib/python3.6/dist-packages/scipy/stats/stats.py:1535: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  "anyway, n=%i" % int(n))
/usr/local/lib/python3.6/dist-packages/scipy/stats/stats.py:1535: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  "anyway, n=%i" % int(n))
/usr/local/lib/python3.6/dist-packages/statsmodels/regression/linear_model.py:1636: RuntimeWarning: divide by zero encountered in double_scalars
  return 1 - self.ssr/self.centered_tss
/usr/local/lib/python3.6/dist-packages/scipy/stats/stats.py:1535: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  "anyway, n=%i" % int(n))

    Intercept     pricehigh  ...  attribute3high  attribute4high
1      5.0000  2.220000e-16  ...    1.998000e-15    1.998000e-15
2      1.3333 -3.333000e-01  ...    3.333000e-01    6.667000e-01
3      5.0000  2.220000e-16  ...    1.998000e-15    1.998000e-15
4      6.0000  2.776000e-17  ...    2.665000e-15    1.998000e-15
5      4.6667 -1.666700e+00  ...    6.667000e-01   -6.667000e-01
6      2.3500 -1.500000e-01  ...    8.000000e-01    2.200000e+00
7      4.6667 -6.667000e-01  ...   -3.333000e-01   -1.666700e+00
8      2.5333 -1.333000e-01  ...    9.333000e-01   -9.333000e-01
9      3.2833  1.167000e-01  ...    1.933300e+00    6.670000e-02
10     3.2000 -3.300000e+00  ...    1.100000e+00   -1.000000e-01
11     1.0000  9.298000e-16  ...    1.305000e-15    5.551000e-16
12     5.0667  2.333000e-01  ...    8.667000e-01   -2.366700e+00
13     6.9000 -6.000000e-01  ...   -1.800000e+00    3.000000e-01
14     4.4000 -1.100000e+00  ...    7.000000e-01    2.300000e+00
15     4.6333 -5.333000e-01  ...    2.333000e-01   -1.233300e+00
16     4.6000 -4.000000e-01  ...    1.300000e+00    2.000000e-01
17     1.9833  3.167000e-01  ...    3.330000e-02    4.966700e+00
18     6.9667  6.333000e-01  ...   -2.433300e+00   -2.066700e+00
19     2.0167 -8.167000e-01  ...    9.667000e-01   -4.667000e-01
20     7.0000 -1.721000e-15  ...    8.882000e-16    1.998000e-15
21     2.6667 -6.667000e-01  ...   -8.333000e-01    3.333000e-01
22     4.4000 -1.000000e-01  ...    2.000000e-01   -7.000000e-01
23     2.0000 -5.000000e-01  ...   -1.500000e+00    3.500000e+00
24     5.1667 -1.667000e-01  ...    6.667000e-01   -6.667000e-01
25     5.9333  2.667000e-01  ...    1.333000e-01   -2.133300e+00
26     6.2167 -1.167000e-01  ...   -2.933300e+00   -5.667000e-01
27     5.8000 -1.200000e+00  ...    4.000000e-01   -1.400000e+00
28     2.5500 -1.450000e+00  ...    3.400000e+00    1.000000e-01
29     5.0833 -8.330000e-02  ...    1.333300e+00    6.667000e-01
30     5.6500 -1.850000e+00  ...    2.000000e-01   -2.000000e-01
31     4.4333  2.667000e-01  ...   -8.667000e-01   -1.633300e+00
32     6.2167 -6.167000e-01  ...    1.066700e+00   -1.066700e+00
33     3.7667 -5.667000e-01  ...   -3.330000e-02   -1.466700e+00
34     2.6833  1.670000e-02  ...   -8.667000e-01   -6.333000e-01
35     3.5500  1.050000e+00  ...   -6.000000e-01    6.000000e-01
36     2.7833  1.167000e-01  ...   -5.667000e-01   -1.433300e+00
37     3.0667  7.333000e-01  ...    8.667000e-01    1.133300e+00
38     6.2000 -3.000000e-01  ...   -9.000000e-01   -1.000000e-01
39     4.7500  1.250000e+00  ...   -5.000000e-01    1.665000e-15
40     3.7500  7.500000e-01  ...    1.554000e-15   -1.500000e+00
41     3.8000 -2.000000e-01  ...    4.000000e-01   -1.400000e+00
42     2.0000  1.943000e-16  ...    8.327000e-16    8.327000e-16
43     4.4000 -1.000000e-01  ...    2.000000e-01   -1.700000e+00

[43 rows x 6 columns]

In [12]:
theresults

    Intercept     pricehigh  ...  attribute3high  attribute4high
1      5.0000  2.220000e-16  ...    1.998000e-15    1.998000e-15
2      1.3333 -3.333000e-01  ...    3.333000e-01    6.667000e-01
3      5.0000  2.220000e-16  ...    1.998000e-15    1.998000e-15
4      6.0000  2.776000e-17  ...    2.665000e-15    1.998000e-15
5      4.6667 -1.666700e+00  ...    6.667000e-01   -6.667000e-01
6      2.3500 -1.500000e-01  ...    8.000000e-01    2.200000e+00
7      4.6667 -6.667000e-01  ...   -3.333000e-01   -1.666700e+00
8      2.5333 -1.333000e-01  ...    9.333000e-01   -9.333000e-01
9      3.2833  1.167000e-01  ...    1.933300e+00    6.670000e-02
10     3.2000 -3.300000e+00  ...    1.100000e+00   -1.000000e-01
11     1.0000  9.298000e-16  ...    1.305000e-15    5.551000e-16
12     5.0667  2.333000e-01  ...    8.667000e-01   -2.366700e+00
13     6.9000 -6.000000e-01  ...   -1.800000e+00    3.000000e-01
14     4.4000 -1.100000e+00  ...    7.000000e-01    2.300000e+00
15     4.6333 -5.333000e-01  ...    2.333000e-01   -1.233300e+00
16     4.6000 -4.000000e-01  ...    1.300000e+00    2.000000e-01
17     1.9833  3.167000e-01  ...    3.330000e-02    4.966700e+00
18     6.9667  6.333000e-01  ...   -2.433300e+00   -2.066700e+00
19     2.0167 -8.167000e-01  ...    9.667000e-01   -4.667000e-01
20     7.0000 -1.721000e-15  ...    8.882000e-16    1.998000e-15
21     2.6667 -6.667000e-01  ...   -8.333000e-01    3.333000e-01
22     4.4000 -1.000000e-01  ...    2.000000e-01   -7.000000e-01
23     2.0000 -5.000000e-01  ...   -1.500000e+00    3.500000e+00
24     5.1667 -1.667000e-01  ...    6.667000e-01   -6.667000e-01
25     5.9333  2.667000e-01  ...    1.333000e-01   -2.133300e+00
26     6.2167 -1.167000e-01  ...   -2.933300e+00   -5.667000e-01
27     5.8000 -1.200000e+00  ...    4.000000e-01   -1.400000e+00
28     2.5500 -1.450000e+00  ...    3.400000e+00    1.000000e-01
29     5.0833 -8.330000e-02  ...    1.333300e+00    6.667000e-01
30     5.6500 -1.850000e+00  ...    2.000000e-01   -2.000000e-01
31     4.4333  2.667000e-01  ...   -8.667000e-01   -1.633300e+00
32     6.2167 -6.167000e-01  ...    1.066700e+00   -1.066700e+00
33     3.7667 -5.667000e-01  ...   -3.330000e-02   -1.466700e+00
34     2.6833  1.670000e-02  ...   -8.667000e-01   -6.333000e-01
35     3.5500  1.050000e+00  ...   -6.000000e-01    6.000000e-01
36     2.7833  1.167000e-01  ...   -5.667000e-01   -1.433300e+00
37     3.0667  7.333000e-01  ...    8.667000e-01    1.133300e+00
38     6.2000 -3.000000e-01  ...   -9.000000e-01   -1.000000e-01
39     4.7500  1.250000e+00  ...   -5.000000e-01    1.665000e-15
40     3.7500  7.500000e-01  ...    1.554000e-15   -1.500000e+00
41     3.8000 -2.000000e-01  ...    4.000000e-01   -1.400000e+00
42     2.0000  1.943000e-16  ...    8.327000e-16    8.327000e-16
43     4.4000 -1.000000e-01  ...    2.000000e-01   -1.700000e+00

[43 rows x 6 columns]

In [13]:
theresults.to_excel('conjointresults.xlsx')